//
//  Document.swift
//  WBSDKGenerator
//
//  Created by xu.shuifeng on 2018/4/11.
//  Copyright © 2018 shuifeng.me. All rights reserved.
//

import Foundation

class Document {
    
    let headerString = "// NOTE: This file is generated by WBSDKGenerator."
    
    let ParametetFolderName: String = "ParameterModels"
    
    let wbFunction: WBFunction
    
    init(wbFunction: WBFunction) {
        self.wbFunction = wbFunction
    }
    
    func generate() {
        
    }
}

// create Request Parameter Model
extension Document {
    
    fileprivate func createParameter() {
        let fileName = "\(wbFunction.category)Parameter.swift"
        let filePath = WBOutputDir.appending("/\(ParametetFolderName)/\(fileName)")
        let fileURL = URL(fileURLWithPath: filePath)
        if !FileManager.default.fileExists(atPath: fileURL.path) {
            var body = ""
            body.append(headerString)
            body.append("\n\n")
            body.append("extension WeiboSDK {\n")
            
            body.append("}")
            if let data = body.data(using: .utf8) {
                try? data.write(to: fileURL)
            }
        }
        
        guard var body = try? String(contentsOfFile: fileURL.path) else {
            return
        }
        body.removeLast()
        body.append("\n")
        body.append(parameterMembers())
        body.append("}")
        if let data = body.data(using: .utf8) {
            try? data.write(to: fileURL)
        }
    }
    
    fileprivate func parameterMembers() -> String {
        var content = ""
        content.append("    public struct \(wbFunction.signature)Parameter {\n")
        for param in wbFunction.parameters {
            content.append("        // \(param.description)\n")
            content.append("        var ")
            content.append("\(param.name): \(swiftTypeFor(param.type))")
            if param.optional {
                content.append("?")
            }
            content.append("\n")
        }
        content.append("    }")
        return content
    }
    
    func parameters() -> String {
        var content = ""
        content.append("\n")
//        for param in wbFunction.parameters {
//            if param.optional {
//                content.append("        if let \(param.name) = \(param.name) {\n")
//                content.append("            params[\"\(param.name)\"] = \(param.name)\n")
//                content.append("        }\n")
//            } else {
//                content.append("        params[\"\(param.name)\"] = \(param.name)\n")
//            }
//        }
        return content
    }
}

// create WeiboSDK+(categroy).swfit
extension Document {
    
    fileprivate func createSDK() {
        let fileName = "WeiboSDK+\(wbFunction.category).swift"
        let filePath = WBOutputDir.appending("/\(fileName)")
        let fileURL = URL(fileURLWithPath: filePath)
        if !FileManager.default.fileExists(atPath: filePath) {
            var body = ""
            body.append(headerString)
            body.append("\n\n")
            body.append("import GenericNetworking \n")
            body.append("\n")
            
            body.append("// MARK: - \(wbFunction.category) related API \n")
            body.append("extension WeiboSDK {\n")
            body.append("}")
            if let data = body.data(using: .utf8) {
                try? data.write(to: fileURL)
            }
        }
        guard var body = try? String(contentsOfFile: fileURL.path) else {
            return
        }
        body.removeLast()
        body.append("\n")
        body.append(weiboMethod())
        body.append("}")
        if let data = body.data(using: .utf8) {
            try? data.write(to: fileURL)
        }
    }
    
    func weiboMethod() -> String {
        
        var content = ""
        content.append("    /// \(wbFunction.description)\n")
        content.append("    ///\n")
        content.append("    /// - Parameters:\n")
        for param in wbFunction.parameters {
            content.append("    ///   - \(param.name): \(param.description)\n")
        }
        content.append("    ///   - completion: Callback\n")
        content.append("    ")
        content.append("public class func \(wbFunction.signature)(")
        
        // TODO
        
        content.append("completion: @escaping GenericNetworkingCompletion<Int>")
        content.append(") {\n")
        content.append("        let path = \"\(wbFunction.path)\"\n")
        content.append("        var params: [String: Any] = [:]\n")
        
        // TODO

        content.append("        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)\n")
        content.append("    ")
        content.append("}\n")
        return content
    }
    
}
