//
//  Document.swift
//  WBSDKGenerator
//
//  Created by xu.shuifeng on 2018/4/11.
//  Copyright © 2018 shuifeng.me. All rights reserved.
//

import Foundation

struct Line {
    
    let content: String
    
    let indent: Indent
    
    static var newLine: Line {
        return Line(content: "\n", indent: .level0)
    }
    
    func text() -> String {
        return indent.rawValue + content + "\n"
    }
}

class Document {
    
    let headerString = "// NOTE: This file is generated by WBSDKGenerator."
    
    static let ParameterFolderName = "ParameterModels"
    
    static let ResponseFolderName = "ResponseModels"
    
    let wbFunction: WBFunction
    
    init(wbFunction: WBFunction) {
        self.wbFunction = wbFunction
    }
    
    func generate() {
        createParameterDocument()
        createSDKDocument()
    }
}

// create Request Parameter Model
extension Document {
    
    fileprivate func createParameterDocument() {
        
        if wbFunction.parameters.count == 0 {
            return
        }
        
        let fileName = "\(wbFunction.category)Parameter.swift"
        let filePath = WBOutputDir.appending("/\(Document.ParameterFolderName)/\(fileName)")
        let fileURL = URL(fileURLWithPath: filePath)
        if !FileManager.default.fileExists(atPath: fileURL.path) {
            var body = ""
            body.append(headerString)
            body.append("\n\n")
            body.append("extension WBParameter {\n")
            
            body.append("    public struct \(wbFunction.category) {\n")
            
            body.append("    }\n")
            body.append("}")
            if let data = body.data(using: .utf8) {
                try? data.write(to: fileURL)
            }
        }
        
        guard var body = try? String(contentsOfFile: fileURL.path) else {
            return
        }
        
        for _ in 0...6 {
            body.removeLast()
        }
    
        body.append("\n")
        body.append(parameterMembers())
        body.append("    }\n")
        body.append("}")
        if let data = body.data(using: .utf8) {
            try? data.write(to: fileURL)
        }
    }
    
    fileprivate func parameterMembers() -> String {
        
        var lines: [Line] = []
        
        lines.append(Line(content: "public class \(wbFunction.signature): NSObject {", indent: .level2))
        for param in wbFunction.parameters {
            lines.append(Line(content: "// \(param.description)", indent: .level3))
            var declaration = "public var \(param.name): \(swiftTypeFor(param.type))"
            if param.optional {
                declaration += "?"
            }
            lines.append(Line(content: declaration, indent: .level3))
        }
        
        let initialProperties = wbFunction.parameters.filter({ return $0.optional == false })
        if initialProperties.count > 0 {
            var initFunction = "public init("
            for property in initialProperties {
                initFunction.append("\(property.name): \(swiftTypeFor(property.type)), ")
            }
            initFunction.removeLast()
            initFunction.removeLast()
            initFunction.append(") {")
            lines.append(Line(content: initFunction, indent: .level3))
            for property in initialProperties {
                lines.append(Line(content: "self.\(property.name) = \(property.name)", indent: .level4))
            }
            lines.append(Line(content: "}", indent: .level3))
        } else {
            lines.append(Line.newLine)
        }
        lines.append(Line(content: "func value() -> [String: Any] {", indent: .level3))
        lines.append(Line(content: "var params: [String: Any] = [:]", indent: .level4))
        for param in wbFunction.parameters {
            if param.optional {
                lines.append(Line(content: "if let \(param.name) = \(param.name) {", indent: .level4))
                lines.append(Line(content: "params[\"\(param.name)\"] = \(param.name)", indent: .level5))
                lines.append(Line(content: "}", indent: .level4))
                
            } else {
                lines.append(Line(content: "params[\"\(param.name)\"] = \(param.name)", indent: .level4))
            }
        }
        lines.append(Line(content: "return params", indent: .level4))
        lines.append(Line(content: "}", indent: .level3))
        lines.append(Line(content: "}", indent: .level2))
    
        var result = ""
        lines.forEach({ result += $0.text() })
        return result
    }
}

// create WeiboSDK+(categroy).swfit
extension Document {
    
    fileprivate func createSDKDocument() {
        let fileName = "WeiboSDK+\(wbFunction.category).swift"
        let filePath = WBOutputDir.appending("/\(fileName)")
        let fileURL = URL(fileURLWithPath: filePath)
        if !FileManager.default.fileExists(atPath: filePath) {
            var body = ""
            body.append(headerString)
            body.append("\n\n")
            body.append("import GenericNetworking \n")
            body.append("\n")
            
            body.append("// MARK: - \(wbFunction.category) related API \n")
            body.append("extension WeiboSDK {\n")
            body.append("\n")
            body.append("    public struct \(wbFunction.category) {\n")
            body.append("    }\n")
            body.append("}")
            if let data = body.data(using: .utf8) {
                try? data.write(to: fileURL)
            }
        }
        guard var body = try? String(contentsOfFile: fileURL.path) else {
            return
        }
        for _ in 0...6 {
            body.removeLast()
        }
        
        body.append("\n")
        body.append(weiboMethod())
        body.append("    }\n")
        body.append("}")
        if let data = body.data(using: .utf8) {
            try? data.write(to: fileURL)
        }
    }
    
    func weiboMethod() -> String {
        var lines: [Line] = []
        lines.append(Line(content: "///\(wbFunction.description)", indent: .level2))
        lines.append(Line(content: "///", indent: .level2))
        lines.append(Line(content: "/// - Parameters:", indent: .level2))
        let type = "WBParameter.\(wbFunction.category).\(wbFunction.signature)"
        if wbFunction.parameters.count > 0 {
            lines.append(Line(content: "///   - param: Refer `\(type)` to see more details. ", indent: .level2))
        }
        lines.append(Line(content: "///   - completion: Callback", indent: .level2))
        
        var signature = "public static func \(wbFunction.signature.lowercaseFirstLetter())("
        if wbFunction.parameters.count > 0 {
            signature.append("param: \(type), ")
        }
        signature.append("completion: @escaping GenericNetworkingCompletion<Int>) {")
        lines.append(Line(content: signature, indent: .level2))
        
        // append body
        lines.append(Line(content: "let path = \"\(wbFunction.path)\"", indent: .level3))
        if wbFunction.parameters.count == 0 {
            lines.append(Line(content: "let params: [String: Any] = [:]", indent: .level3))
        } else {
            lines.append(Line(content: "let params = param.value()", indent: .level3))
        }
        switch wbFunction.method {
        case .GET:
            lines.append(Line(content: "GenericNetworking.getJSON(path: path, parameters: params, completion: completion)", indent: .level3))
        case .POST:
            lines.append(Line(content: "GenericNetworking.postJSON(path: path, parameters: params, completion: completion)", indent: .level3))
        }
        lines.append(Line(content: "}", indent: .level2))
        
        var result = ""
        lines.forEach({ result += $0.text() })
        return result
    }
    
}
