// NOTE: This file is generated by WBSDKGenerator.

extension WeiboSDK {

    public struct Common_code_to_locationParameter {

        // 需要查询的地址编码，多个之间用逗号分隔。
        var codes: String

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["codes"] = codes
            return params
        }
    }

    public struct Common_get_cityParameter {

        // 省份的省份代码。
        var province: String

        // 城市的首字母，a-z，可为空代表返回全部，默认为全部。
        var capital: String?

        // 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
        var language: String?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["province"] = province
            if let capital = capital {
                params["capital"] = capital
            }
            if let language = language {
                params["language"] = language
            }
            return params
        }
    }

    public struct Common_get_countryParameter {

        // 国家的首字母，a-z，可为空代表返回全部，默认为全部。
        var capital: String?

        // 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
        var language: String?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let capital = capital {
                params["capital"] = capital
            }
            if let language = language {
                params["language"] = language
            }
            return params
        }
    }

    public struct Common_get_provinceParameter {

        // 国家的国家代码。
        var country: String

        // 省份的首字母，a-z，可为空代表返回全部，默认为全部。
        var capital: String?

        // 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
        var language: String?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["country"] = country
            if let capital = capital {
                params["capital"] = capital
            }
            if let language = language {
                params["language"] = language
            }
            return params
        }
    }

    public struct Common_get_timezoneParameter {

        // 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
        var language: String?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let language = language {
                params["language"] = language
            }
            return params
        }
    }
}