// NOTE: This file is generated by WBSDKGenerator.

extension WeiboSDK {

    public struct Comments_by_meParameter {

        // 若指定此参数，则返回ID比since_id大的评论（即比since_id时间晚的评论），默认为0。
        var since_id: Int64?

        // 若指定此参数，则返回ID小于或等于max_id的评论，默认为0。
        var max_id: Int64?

        // 单页返回的记录条数，默认为50。
        var count: Int?

        // 返回结果的页码，默认为1。
        var page: Int?

        // 来源筛选类型，0：全部、1：来自微博的评论、2：来自微群的评论，默认为0。
        var filter_by_source: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let since_id = since_id {
                params["since_id"] = since_id
            }
            if let max_id = max_id {
                params["max_id"] = max_id
            }
            if let count = count {
                params["count"] = count
            }
            if let page = page {
                params["page"] = page
            }
            if let filter_by_source = filter_by_source {
                params["filter_by_source"] = filter_by_source
            }
            return params
        }
    }

    public struct Comments_destroyParameter {

        // 要删除的评论ID，只能删除登录用户自己发布的评论。
        var cid: Int64

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["cid"] = cid
            return params
        }
    }

    public struct Comments_destroy_batchParameter {

        // 需要删除的评论ID，用半角逗号隔开，最多20个。
        var cids: Int64

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["cids"] = cids
            return params
        }
    }

    public struct Comments_mentionsParameter {

        // 若指定此参数，则返回ID比since_id大的评论（即比since_id时间晚的评论），默认为0。
        var since_id: Int64?

        // 若指定此参数，则返回ID小于或等于max_id的评论，默认为0。
        var max_id: Int64?

        // 单页返回的记录条数，默认为50。
        var count: Int?

        // 返回结果的页码，默认为1。
        var page: Int?

        // 作者筛选类型，0：全部、1：我关注的人、2：陌生人，默认为0。
        var filter_by_author: Int?

        // 来源筛选类型，0：全部、1：来自微博的评论、2：来自微群的评论，默认为0。
        var filter_by_source: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let since_id = since_id {
                params["since_id"] = since_id
            }
            if let max_id = max_id {
                params["max_id"] = max_id
            }
            if let count = count {
                params["count"] = count
            }
            if let page = page {
                params["page"] = page
            }
            if let filter_by_author = filter_by_author {
                params["filter_by_author"] = filter_by_author
            }
            if let filter_by_source = filter_by_source {
                params["filter_by_source"] = filter_by_source
            }
            return params
        }
    }

    public struct Comments_showParameter {

        // 需要查询的微博ID。
        var id: Int64

        // 若指定此参数，则返回ID比since_id大的评论（即比since_id时间晚的评论），默认为0。
        var since_id: Int64?

        // 若指定此参数，则返回ID小于或等于max_id的评论，默认为0。
        var max_id: Int64?

        // 单页返回的记录条数，默认为50。
        var count: Int?

        // 返回结果的页码，默认为1。
        var page: Int?

        // 作者筛选类型，0：全部、1：我关注的人、2：陌生人，默认为0。
        var filter_by_author: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["id"] = id
            if let since_id = since_id {
                params["since_id"] = since_id
            }
            if let max_id = max_id {
                params["max_id"] = max_id
            }
            if let count = count {
                params["count"] = count
            }
            if let page = page {
                params["page"] = page
            }
            if let filter_by_author = filter_by_author {
                params["filter_by_author"] = filter_by_author
            }
            return params
        }
    }

    public struct Comments_show_batchParameter {

        // 需要查询的批量评论ID，用半角逗号分隔，最大50。
        var cids: Int64

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["cids"] = cids
            return params
        }
    }

    public struct Comments_timelineParameter {

        // 若指定此参数，则返回ID比since_id大的评论（即比since_id时间晚的评论），默认为0。
        var since_id: Int64?

        // 若指定此参数，则返回ID小于或等于max_id的评论，默认为0。
        var max_id: Int64?

        // 单页返回的记录条数，默认为50。
        var count: Int?

        // 返回结果的页码，默认为1。
        var page: Int?

        // 返回值中user字段开关，0：返回完整user字段、1：user字段仅返回user_id，默认为0。
        var trim_user: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let since_id = since_id {
                params["since_id"] = since_id
            }
            if let max_id = max_id {
                params["max_id"] = max_id
            }
            if let count = count {
                params["count"] = count
            }
            if let page = page {
                params["page"] = page
            }
            if let trim_user = trim_user {
                params["trim_user"] = trim_user
            }
            return params
        }
    }

    public struct Comments_to_meParameter {

        // 若指定此参数，则返回ID比since_id大的评论（即比since_id时间晚的评论），默认为0。
        var since_id: Int64?

        // 若指定此参数，则返回ID小于或等于max_id的评论，默认为0。
        var max_id: Int64?

        // 单页返回的记录条数，默认为50。
        var count: Int?

        // 返回结果的页码，默认为1。
        var page: Int?

        // 作者筛选类型，0：全部、1：我关注的人、2：陌生人，默认为0。
        var filter_by_author: Int?

        // 来源筛选类型，0：全部、1：来自微博的评论、2：来自微群的评论，默认为0。
        var filter_by_source: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let since_id = since_id {
                params["since_id"] = since_id
            }
            if let max_id = max_id {
                params["max_id"] = max_id
            }
            if let count = count {
                params["count"] = count
            }
            if let page = page {
                params["page"] = page
            }
            if let filter_by_author = filter_by_author {
                params["filter_by_author"] = filter_by_author
            }
            if let filter_by_source = filter_by_source {
                params["filter_by_source"] = filter_by_source
            }
            return params
        }
    }
}