// NOTE: This file is generated by WBSDKGenerator.

extension WBParameter {
    public struct Emotionsjson {

        public class Emotions: NSObject {

            // 表情类别，face：普通表情、ani：魔法表情、cartoon：动漫表情，默认为face。
            public var type: String?

            // 语言类别，cnname：简体、twname：繁体，默认为cnname。
            public var language: String?

            func value() -> [String: Any] {
                var params: [String: Any] = [:]
                if let type = type {
                    params["type"] = type
                }
                if let language = language {
                    params["language"] = language
                }
                return params
            }
        }
    }
}