// NOTE: This file is generated by WBSDKGenerator.

extension WeiboSDK {

    public struct Friendships_followersParameter {

        // 需要查询的用户UID。
        var uid: Int64?

        // 需要查询的用户昵称。
        var screen_name: String?

        // 单页返回的记录条数，默认为5，最大不超过5。
        var count: Int?

        // 返回结果的游标，下一页用返回值里的next_cursor，上一页用previous_cursor，默认为0。
        var cursor: Int?

        // 返回值中user字段中的status字段开关，0：返回完整status字段、1：status字段仅返回status_id，默认为1。
        var trim_status: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let uid = uid {
                params["uid"] = uid
            }
            if let screen_name = screen_name {
                params["screen_name"] = screen_name
            }
            if let count = count {
                params["count"] = count
            }
            if let cursor = cursor {
                params["cursor"] = cursor
            }
            if let trim_status = trim_status {
                params["trim_status"] = trim_status
            }
            return params
        }
    }

    public struct Friendships_friendsParameter {

        // 需要查询的用户UID。
        var uid: Int64?

        // 需要查询的用户昵称。
        var screen_name: String?

        // 单页返回的记录条数，默认为5，最大不超过5。
        var count: Int?

        // 返回结果的游标，下一页用返回值里的next_cursor，上一页用previous_cursor，默认为0。
        var cursor: Int?

        // 返回值中user字段中的status字段开关，0：返回完整status字段、1：status字段仅返回status_id，默认为1。
        var trim_status: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let uid = uid {
                params["uid"] = uid
            }
            if let screen_name = screen_name {
                params["screen_name"] = screen_name
            }
            if let count = count {
                params["count"] = count
            }
            if let cursor = cursor {
                params["cursor"] = cursor
            }
            if let trim_status = trim_status {
                params["trim_status"] = trim_status
            }
            return params
        }
    }

    public struct Friendships_idsParameter {

        // 需要查询的用户UID。
        var uid: Int64?

        // 需要查询的用户昵称。
        var screen_name: String?

        // 单页返回的记录条数，默认为5，最大不超过5。
        var count: Int?

        // 返回结果的游标，下一页用返回值里的next_cursor，上一页用previous_cursor，默认为0。
        var cursor: Int?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let uid = uid {
                params["uid"] = uid
            }
            if let screen_name = screen_name {
                params["screen_name"] = screen_name
            }
            if let count = count {
                params["count"] = count
            }
            if let cursor = cursor {
                params["cursor"] = cursor
            }
            return params
        }
    }
}