// NOTE: This file is generated by WBSDKGenerator.
 
extension WBParameter {
    public struct Search {
 
        public class Topics: NSObject {
 
            // 搜索的话题关键字，必须进行URLencode，utf-8编码。
            public var q: String
            // 单页返回的记录条数，默认为10，最大为50。
            public var count: Int?
            // 返回结果的页码，默认为1。
            public var page: Int?
 
            public init(q: String) {
                self.q = q
            }
 
            func value() -> [String: Any] {
                var params: [String: Any] = [:]
                params["q"] = q
                if let count = count {
                    params["count"] = count
                }
                if let page = page {
                    params["page"] = page
                }
                return params
            }
        }
    }
}
