// NOTE: This file is generated by WBSDKGenerator.

extension WeiboSDK {

    public struct Short_Url_countsParameter {

        // 需要取得分享数的短链接，需要URLencoded，最多不超过20个。
        var url_short: String

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["url_short"] = url_short
            return params
        }
    }

    public struct Short_Url_expandParameter {

        // 需要还原的短链接，需要URLencoded，最多不超过20个 。
        var url_short: String

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["url_short"] = url_short
            return params
        }
    }

    public struct Short_Url_shortenParameter {

        // 需要转换的长链接，需要URLencoded，最多不超过20个。
        var url_long: String

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["url_long"] = url_long
            return params
        }
    }
}