// NOTE: This file is generated by WBSDKGenerator.

extension WeiboSDK {

    public struct Users_countsParameter {

        // 需要获取数据的用户UID，多个之间用逗号分隔，最多不超过100个。
        var uids: String

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["uids"] = uids
            return params
        }
    }

    public struct Users_domain_showParameter {

        // 需要查询的个性化域名。
        var domain: String

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            params["domain"] = domain
            return params
        }
    }

    public struct Users_showParameter {

        // 需要查询的用户ID。
        var uid: Int64?

        // 需要查询的用户昵称。
        var screen_name: String?

        func value() -> [String: Any] {
            var params: [String: Any] = [:]
            if let uid = uid {
                params["uid"] = uid
            }
            if let screen_name = screen_name {
                params["screen_name"] = screen_name
            }
            return params
        }
    }
}