// NOTE: This file is generated by WBSDKGenerator.

extension WBParameter {
    public struct Users {

        public class Counts: NSObject {

            // 需要获取数据的用户UID，多个之间用逗号分隔，最多不超过100个。
            public var uids: String

            public init(uids: String) {
                self.uids = uids
             }
            func value() -> [String: Any] {
                var params: [String: Any] = [:]
                params["uids"] = uids
                return params
            }
        }

        public class DomainShow: NSObject {

            // 需要查询的个性化域名。
            public var domain: String

            public init(domain: String) {
                self.domain = domain
             }
            func value() -> [String: Any] {
                var params: [String: Any] = [:]
                params["domain"] = domain
                return params
            }
        }

        public class Show: NSObject {

            // 需要查询的用户ID。
            public var uid: Int64?

            // 需要查询的用户昵称。
            public var screen_name: String?

            func value() -> [String: Any] {
                var params: [String: Any] = [:]
                if let uid = uid {
                    params["uid"] = uid
                }
                if let screen_name = screen_name {
                    params["screen_name"] = screen_name
                }
                return params
            }
        }
    }
}