// NOTE: This file is generated by WBSDKGenerator.

public struct CommentManageInfo : Codable {

    public var approvalCommentType: Int? 

    public var commentPermissionType: Int? 

    enum CodingKeys: String, CodingKey {
        case approvalCommentType = "approval_comment_type"
        case commentPermissionType = "comment_permission_type"
    }
}
