// NOTE: This file is generated by WBSDKGenerator.

public struct HomeTimelineResponse : Codable {

    // 微博流内的推广微博ID
    public var ad: [String]? 

    public var advertises: [String]? 

    public var hasUnread: Int? 

    public var hasvisible: Bool? 

    public var interval: Int? 

    public var maxId: Int? 

    public var nextCursor: Int? 

    public var previousCursor: Int? 

    public var sinceId: Int? 

    public var statuses: Statuses? 

    public var totalNumber: Int? 

    public var uveBlank: Int? 

    enum CodingKeys: String, CodingKey {
        case ad = "ad"
        case advertises = "advertises"
        case hasUnread = "has_unread"
        case hasvisible = "hasvisible"
        case interval = "interval"
        case maxId = "max_id"
        case nextCursor = "next_cursor"
        case previousCursor = "previous_cursor"
        case sinceId = "since_id"
        case statuses = "statuses"
        case totalNumber = "total_number"
        case uveBlank = "uve_blank"
    }
}
