// NOTE: This file is generated by WBSDKGenerator.

public struct Insecurity : Codable {

    public var sexualContent: Bool? 

    enum CodingKeys: String, CodingKey {
        case sexualContent = "sexual_content"
    }
}
