// NOTE: This file is generated by WBSDKGenerator.

public struct User : Codable {

    public var allowAllActMsg: Bool? 

    public var allowAllComment: Bool? 

    public var avatarHd: String? 

    public var avatarLarge: String? 

    public var biFollowersCount: Int? 

    public var blockApp: Int? 

    public var blockWord: Int? 

    public var city: String? 

    public var m_class: Int? 

    public var coverImage: String? 

    public var coverImagePhone: String? 

    // 微博创建时间
    public var createdAt: String? 

    public var creditScore: Int? 

    public var m_description: String? 

    public var domain: String? 

    public var favouritesCount: Int? 

    public var followMe: Bool? 

    public var followersCount: Int? 

    public var following: Bool? 

    public var friendsCount: Int? 

    public var gender: String? 

    public var geoEnabled: Bool? 

    public var hasServiceTel: Bool? 

    // 微博ID
    public var id: Int? 

    // 字符串型的微博ID
    public var idstr: String? 

    public var insecurity: Insecurity? 

    public var lang: String? 

    public var like: Bool? 

    public var likeMe: Bool? 

    public var location: String? 

    public var mbrank: Int? 

    public var mbtype: Int? 

    public var name: String? 

    public var onlineStatus: Int? 

    public var pagefriendsCount: Int? 

    public var profileImageUrl: String? 

    public var profileUrl: String? 

    public var province: String? 

    public var ptype: Int? 

    public var remark: String? 

    public var screenName: String? 

    public var star: Int? 

    public var statusesCount: Int? 

    public var storyReadState: Int? 

    public var urank: Int? 

    public var url: String? 

    public var userAbility: Int? 

    public var vclubMember: Int? 

    public var verified: Bool? 

    public var verifiedContactEmail: String? 

    public var verifiedContactMobile: String? 

    public var verifiedContactName: String? 

    public var verifiedLevel: Int? 

    public var verifiedReason: String? 

    public var verifiedReasonModified: String? 

    public var verifiedReasonUrl: String? 

    public var verifiedSource: String? 

    public var verifiedSourceUrl: String? 

    public var verifiedState: Int? 

    public var verifiedTrade: String? 

    public var verifiedType: Int? 

    public var verifiedTypeExt: Int? 

    public var weihao: String? 

    enum CodingKeys: String, CodingKey {
        case allowAllActMsg = "allow_all_act_msg"
        case allowAllComment = "allow_all_comment"
        case avatarHd = "avatar_hd"
        case avatarLarge = "avatar_large"
        case biFollowersCount = "bi_followers_count"
        case blockApp = "block_app"
        case blockWord = "block_word"
        case city = "city"
        case m_class = "class"
        case coverImage = "cover_image"
        case coverImagePhone = "cover_image_phone"
        case createdAt = "created_at"
        case creditScore = "credit_score"
        case m_description = "description"
        case domain = "domain"
        case favouritesCount = "favourites_count"
        case followMe = "follow_me"
        case followersCount = "followers_count"
        case following = "following"
        case friendsCount = "friends_count"
        case gender = "gender"
        case geoEnabled = "geo_enabled"
        case hasServiceTel = "has_service_tel"
        case id = "id"
        case idstr = "idstr"
        case insecurity = "insecurity"
        case lang = "lang"
        case like = "like"
        case likeMe = "like_me"
        case location = "location"
        case mbrank = "mbrank"
        case mbtype = "mbtype"
        case name = "name"
        case onlineStatus = "online_status"
        case pagefriendsCount = "pagefriends_count"
        case profileImageUrl = "profile_image_url"
        case profileUrl = "profile_url"
        case province = "province"
        case ptype = "ptype"
        case remark = "remark"
        case screenName = "screen_name"
        case star = "star"
        case statusesCount = "statuses_count"
        case storyReadState = "story_read_state"
        case urank = "urank"
        case url = "url"
        case userAbility = "user_ability"
        case vclubMember = "vclub_member"
        case verified = "verified"
        case verifiedContactEmail = "verified_contact_email"
        case verifiedContactMobile = "verified_contact_mobile"
        case verifiedContactName = "verified_contact_name"
        case verifiedLevel = "verified_level"
        case verifiedReason = "verified_reason"
        case verifiedReasonModified = "verified_reason_modified"
        case verifiedReasonUrl = "verified_reason_url"
        case verifiedSource = "verified_source"
        case verifiedSourceUrl = "verified_source_url"
        case verifiedState = "verified_state"
        case verifiedTrade = "verified_trade"
        case verifiedType = "verified_type"
        case verifiedTypeExt = "verified_type_ext"
        case weihao = "weihao"
    }
}
