// NOTE: This file is generated by WBSDKGenerator.

public struct Visible : Codable {

    public var listId: Int? 

    public var type: Int? 

    enum CodingKeys: String, CodingKey {
        case listId = "list_id"
        case type = "type"
    }
}
