//
//  APIGenerator.swift
//  WBSDKGenerator
//
//  Created by xu.shuifeng on 2018/4/11.
//  Copyright © 2018 shuifeng.me. All rights reserved.
//

import Foundation

class APIGenerator {
    
    let headerString = "// NOTE: This file is generated by WBSDKGenerator."
    
    let filename: String
    
    init(filename: String) {
        self.filename = filename
    }
    
    func generate() {
        
        var body = ""
        body.append(headerString)
        body.append("\n\n")
        body.append("import GenericNetworking")
        
        body.append("// MARK: - XX related API\n")
        body.append("extension WeiboSDK {\n")
        
        body.append("}")
    }
    
    func generateFunc(_ f: WBFunction) -> String {
        
        var content = ""
        content.append("/// \(f.description)\n")
        content.append("///\n")
        content.append("/// - Parameters\n")
        content.append("public class func \(f.signature)(")
        
        content.append("}\n")
        return content
    }
}
