// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Common related API 
extension WeiboSDK {

    /// 通过地址编码获取地址名称
    ///
    /// - Parameters:
    ///   - codes: 需要查询的地址编码，多个之间用逗号分隔。
    ///   - completion: Callback
    public class func Common_code_to_location(param: Common_code_to_locationParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/common/code_to_location.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取城市列表
    ///
    /// - Parameters:
    ///   - province: 省份的省份代码。
    ///   - capital: 城市的首字母，a-z，可为空代表返回全部，默认为全部。
    ///   - language: 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
    ///   - completion: Callback
    public class func Common_get_city(param: Common_get_cityParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/common/get_city.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取国家列表
    ///
    /// - Parameters:
    ///   - capital: 国家的首字母，a-z，可为空代表返回全部，默认为全部。
    ///   - language: 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
    ///   - completion: Callback
    public class func Common_get_country(param: Common_get_countryParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/common/get_country.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取省份列表
    ///
    /// - Parameters:
    ///   - country: 国家的国家代码。
    ///   - capital: 省份的首字母，a-z，可为空代表返回全部，默认为全部。
    ///   - language: 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
    ///   - completion: Callback
    public class func Common_get_province(param: Common_get_provinceParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/common/get_province.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取时区配置表
    ///
    /// - Parameters:
    ///   - language: 返回的语言版本，zh-cn：简体中文、zh-tw：繁体中文、english：英文，默认为zh-cn。
    ///   - completion: Callback
    public class func Common_get_timezone(param: Common_get_timezoneParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/common/get_timezone.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}