// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Search related API 
extension WeiboSDK {

    /// 搜索某一话题下的微博
    ///
    /// - Parameters:
    ///   - q: 搜索的话题关键字，必须进行URLencode，utf-8编码。
    ///   - count: 单页返回的记录条数，默认为10，最大为50。
    ///   - page: 返回结果的页码，默认为1。
    ///   - completion: Callback
    public class func SearchTopics(param: WBParameter.Search.Topics,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/search/topics.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}