// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Short_Url related API 
extension WeiboSDK {

    /// 获取短链接在微博上的微博评论数
    ///
    /// - Parameters:
    ///   - url_short: 需要取得分享数的短链接，需要URLencoded，最多不超过20个。
    ///   - completion: Callback
    public class func Short_Url_counts(param: Short_Url_countsParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/short_url/comment/counts.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 短链转长链
    ///
    /// - Parameters:
    ///   - url_short: 需要还原的短链接，需要URLencoded，最多不超过20个 。
    ///   - completion: Callback
    public class func Short_Url_expand(param: Short_Url_expandParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/short_url/expand.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 长链转短链
    ///
    /// - Parameters:
    ///   - url_long: 需要转换的长链接，需要URLencoded，最多不超过20个。
    ///   - completion: Callback
    public class func Short_Url_shorten(param: Short_Url_shortenParameter,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/short_url/shorten.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}