// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Users related API 
extension WeiboSDK {

    /// 批量获取用户的粉丝数、关注数、微博数
    ///
    /// - Parameters:
    ///   - access_token: 采用OAuth授权方式为必填参数，OAuth授权后获得。
    ///   - uids: 需要获取数据的用户UID，多个之间用逗号分隔，最多不超过100个。
    ///   - completion: Callback
    public class func Users_counts(access_token: String, uids: String, completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/users/counts.json"
        var params: [String: Any] = [:]
        params["access_token"] = access_token
        params["uids"] = uids
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 通过个性域名获取用户信息
    ///
    /// - Parameters:
    ///   - access_token: 采用OAuth授权方式为必填参数，OAuth授权后获得。
    ///   - domain: 需要查询的个性化域名。
    ///   - completion: Callback
    public class func Users_domain_show(access_token: String, domain: String, completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/users/domain_show.json"
        var params: [String: Any] = [:]
        params["access_token"] = access_token
        params["domain"] = domain
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取用户信息
    ///
    /// - Parameters:
    ///   - access_token: 采用OAuth授权方式为必填参数，OAuth授权后获得。
    ///   - uid: 需要查询的用户ID。
    ///   - screen_name: 需要查询的用户昵称。
    ///   - completion: Callback
    public class func Users_show(access_token: String, uid: Int64?, screen_name: String?, completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/users/show.json"
        var params: [String: Any] = [:]
        params["access_token"] = access_token
        if let uid = uid {
            params["uid"] = uid
        }
        if let screen_name = screen_name {
            params["screen_name"] = screen_name
        }
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}