// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Search related API 
extension WeiboSDK {

    public struct Search {

        ///搜索某一话题下的微博
        ///
        /// - Parameters:
        ///   - param: Refer `WBParameter.Search.Topics` to see more details. 
        ///   - completion: Callback
        public static func topics(param: WBParameter.Search.Topics, completion: @escaping GenericNetworkingCompletion<Int>) {
            let path = "/2/search/topics.json"
            let params = param.value()
            GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
        }
    }
}