// NOTE: This file is generated by WBSDKGenerator.
 
import GenericNetworking
 
// MARK: - Users Related API
extension WeiboSDK {
 
    public struct Users {
 
        ///批量获取用户的粉丝数、关注数、微博数
        ///
        /// - Parameters:
        ///   - param: Refer `WBParameter.Users.Counts` to see more details. 
        ///   - completion: Callback
        public static func counts(param: WBParameter.Users.Counts, completion: @escaping GenericNetworkingCompletion<Int>) {
            let path = "/2/users/counts.json"
            var params = param.value()
            if let token = WeiboSDK.accessToken {
                params["access_token"] = token
            }
            GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
        }
 
        ///通过个性域名获取用户信息
        ///
        /// - Parameters:
        ///   - param: Refer `WBParameter.Users.DomainShow` to see more details. 
        ///   - completion: Callback
        public static func domainShow(param: WBParameter.Users.DomainShow, completion: @escaping GenericNetworkingCompletion<Int>) {
            let path = "/2/users/domain_show.json"
            var params = param.value()
            if let token = WeiboSDK.accessToken {
                params["access_token"] = token
            }
            GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
        }
 
        ///获取用户信息
        ///
        /// - Parameters:
        ///   - param: Refer `WBParameter.Users.Show` to see more details. 
        ///   - completion: Callback
        public static func show(param: WBParameter.Users.Show, completion: @escaping GenericNetworkingCompletion<Int>) {
            let path = "/2/users/show.json"
            var params = param.value()
            if let token = WeiboSDK.accessToken {
                params["access_token"] = token
            }
            GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
        }
    }
}
