// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Search related API 
extension WeiboSDK {

    /// 搜索某一话题下的微博
    ///
    /// - Parameters:
    ///   - Topics: Refer `WBParameter.Search.Topics` to see more details. 
    ///   - completion: Callback
    public class func SearchTopics(param: WBParameter.Search.Topics,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/search/topics.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}