// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Friendships related API 
extension WeiboSDK {

    /// 获取用户粉丝列表
    ///
    /// - Parameters:
    ///   - Followers: Refer `WBParameter.Friendships.Followers` to see more details. 
    ///   - completion: Callback
    public class func FriendshipsFollowers(param: WBParameter.Friendships.Followers,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/friendships/followers.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取用户的关注列表
    ///
    /// - Parameters:
    ///   - Friends: Refer `WBParameter.Friendships.Friends` to see more details. 
    ///   - completion: Callback
    public class func FriendshipsFriends(param: WBParameter.Friendships.Friends,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/friendships/friends.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取用户粉丝UID列表
    ///
    /// - Parameters:
    ///   - Ids: Refer `WBParameter.Friendships.Ids` to see more details. 
    ///   - completion: Callback
    public class func FriendshipsIds(param: WBParameter.Friendships.Ids,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/friendships/followers/ids.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 获取两个用户之间是否存在关注关系
    ///
    /// - Parameters:
    ///   - Show: Refer `WBParameter.Friendships.Show` to see more details. 
    ///   - completion: Callback
    public class func FriendshipsShow(param: WBParameter.Friendships.Show,completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/friendships/show.json"
        let params = param.value()
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}