// NOTE: This file is generated by WBSDKGenerator.

import GenericNetworking 

// MARK: - Short_Url related API 
extension WeiboSDK {

    /// 获取短链接在微博上的微博评论数
    ///
    /// - Parameters:
    ///   - url_short: 需要取得分享数的短链接，需要URLencoded，最多不超过20个。
    ///   - completion: Callback
    public class func Short_Url_counts(url_short: String, completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/short_url/comment/counts.json"
        var params: [String: Any] = [:]
        params["url_short"] = url_short
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 短链转长链
    ///
    /// - Parameters:
    ///   - url_short: 需要还原的短链接，需要URLencoded，最多不超过20个 。
    ///   - completion: Callback
    public class func Short_Url_expand(url_short: String, completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/short_url/expand.json"
        var params: [String: Any] = [:]
        params["url_short"] = url_short
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }

    /// 长链转短链
    ///
    /// - Parameters:
    ///   - url_long: 需要转换的长链接，需要URLencoded，最多不超过20个。
    ///   - completion: Callback
    public class func Short_Url_shorten(url_long: String, completion: @escaping GenericNetworkingCompletion<Int>) {
        let path = "/2/short_url/shorten.json"
        var params: [String: Any] = [:]
        params["url_long"] = url_long
        GenericNetworking.getJSON(path: path, parameters: params, completion: completion)
    }
}